repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']  # Allow files up to 1MB (adjust as needed)
        exclude: '\.ipynb$'  # Exclude notebooks from size check
      - id: check-merge-conflict
      - id: detect-private-key

  # Modern Python formatter and linter (replaces Black + isort + Flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix, --line-length=79]
      - id: ruff-format
        args: [--line-length=79]

  # Python version upgrader
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]  # Updated to Python 3.10+

  # SQL linting and formatting
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: [sqlfluff-templater-dbt]
      - id: sqlfluff-fix
        additional_dependencies: [sqlfluff-templater-dbt]

  # Jupyter notebooks cleaning (removes outputs/metadata)
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  # Jupyter notebooks formatting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        args: [--fix, --line-length=79]
        additional_dependencies: [ruff==0.8.4]

  # Custom commit message standard enforcement
  - repo: local
    hooks:
      - id: commit-msg-check
        name: Enforce commit message standard
        entry: python3 .pre-commit-hooks/commit_msg_check.py
        language: system
        stages: [commit-msg]

# Global excludes
exclude: ^(notebooks/data/|data/raw/|data/processed/).*\.(csv|zip|h5|txt|parquet)$
